name: motofinance
description: "Controle financeiro para motociclistas autônomos."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  sqflite: ^2.4.1
  path: ^1.9.1
  intl: ^0.20.2
  sqflite_common_ffi: ^2.3.0
  flutter_native_splash: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/android_playstore_512x512.png"

flutter_native_splash:
  color: "#121212"
  background_image: assets/splash/splash.png  # ocupa a tela toda
  android: true
  ios: true
  color_dark: "#121212"
  background_image_dark: assets/splash/splash.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/moto.png